name: Testing

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  build:

    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run
        env:
          NAMESPACE_NAME: 'foo.bar'
        run: |
          echo "test"
