name: Merge PR
on:
  pull_request:
    types: [closed]
jobs:
  mergePullRequest:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name : GITHUB CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name : Echo PR title
        run: echo "${{ github.event.pull_request.title }}"